version: 2.0

jobs:
  test:
    machine: true
    working_directory: ~/pydst
    environment: 
    - PY_PATH: /opt/circleci/.pyenv/versions/3.6.3/bin/

    steps:
      - checkout
      - run:
          name: "Preparing Python env"
          command: |
            pyenv install 3.6.3
            pyenv global 3.6.3
            python3 -m venv ../venv

      - run:
          name: "Run flake 8"
          command: |
            export PATH=$PATH:$PY_PATH
            pip3.6 install -U flake8
            flake8 pydst/*


      - run:
          name: "Instaling the project"
          command: |
            . ../venv/bin/activate
            python3.6 setup.py install

      - run:
          name: "Run python3 tests"
          command: |
            . ../venv/bin/activate
            PYTHONPATH=$(pwd) python3.6 -m unittest discover -s tests/ -p '*.py' # 3.6 

workflows:
  version: 2

  build-and-test:
    jobs:
      - test
